### ISSUE TITLE
memcpy typo?

### ISSUE THREAD

**Issue by DavidZemon** [totalspectrum/proplib#1]
Should there be an "else" on [line 45](https://github.com/totalspectrum/proplib/blob/e54fd9572c80619ef6a85a13f66391cbef7b9c51/string/memcpy.c#L45) of memcpy.c?

**Comment by totalspectrum** [comment]
No, but there should be a comment :). The second half of the code finishes whatever didn't get done in the first loop. For example, if the length is odd then the first loop will only copy the word aligned part, leaving a small bit at the end to be picked up by the default.
